# Generated by Django 3.2.12 on 2022-04-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.RemoveField(
            model_name='operationlog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='device',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='OperationLog',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
