# Generated by Django 4.2.16 on 2024-11-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='device',
        ),
    ]
